name: CI

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Build
        run: |
          npm i pnpm -g && pnpm i
          pnpm build:production

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          ACCESS_TOKEN: ${{ secrets.PRODUCTION_HUB_PAGE }}
          BRANCH: gh-pages # 部署到 gh-pages 分支
          FOLDER: docs-dist # 生成的静态文件存放的地方
